package io.royaloaklabs.supergenki.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.io.*;

public class DictionaryHelper extends SQLiteOpenHelper {
  private static final String TAG = DictionaryHelper.class.getSimpleName();
  private static final String DATABASE_NAME = "jisho-main.db";
  private static final int DATABASE_VERSION = 3;

  private final Context context;

  public DictionaryHelper(Context context) {
    super(context, DATABASE_NAME, null, DATABASE_VERSION);
    this.context = context;
    Log.d(TAG, "Loading DB");
    if(this.hasNoDatabase()) {
      try {
        this.copyInternalDatabase();
      } catch(IOException e) {
        Log.e(TAG, "IOException in Constructor", e);
      }
    }

    SQLiteDatabase db = SQLiteDatabase.openDatabase(this.context.getDatabasePath(DATABASE_NAME).getAbsolutePath(), null, SQLiteDatabase.OPEN_READONLY);
    int version = db.getVersion();
    db.close();

    if(version < DATABASE_VERSION) {
      try {
        Log.d(TAG, "Upgrading SQL Database");
        File databaseFile = this.context.getDatabasePath(DATABASE_NAME);
        SQLiteDatabase.deleteDatabase(databaseFile);
        this.copyInternalDatabase();
      } catch(IOException e) {
        Log.e(TAG, "IOException in onUpgrade", e);
      }
    }
  }

  @Override
  public void onCreate(SQLiteDatabase db) {
    // TODO Autogenerated onCreate method
  }

  @Override
  public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    // TODO Autogenerated onUpgrade method
  }

  private boolean hasNoDatabase() {
    File db = this.context.getDatabasePath(DATABASE_NAME);
    if(db.length() == 0) {
      return true;
    }
    return false;
  }

  private void copyInternalDatabase() throws IOException {
    File databaseFile = this.context.getDatabasePath(DATABASE_NAME);

    if(!databaseFile.exists()) {
      if(!databaseFile.getParentFile().exists()) {
        databaseFile.getParentFile().mkdir();
      }
    }

    InputStream is = this.context.getAssets().open(DATABASE_NAME);
    OutputStream os = new FileOutputStream(databaseFile);

    byte[] buffer = new byte[1028];
    int length;
    while((length = is.read(buffer)) > 0) {
      os.write(buffer, 0, length);
    }

    os.flush();

    is.close();
    os.close();
  }
}
